title:             RabbitBeta
email:             betaneverstop@gmail.com
description:       不管遇到什么勇敢专注才是真理
author:            Rabbit Beta
baseurl:           ""
url:               "http://betawen.github.io"
favicon:           "/img/favicon.ico"
sass:
  sass_dir: _sass
  style: compressed
# Social Profiles
twitter_username:  
github_username:   betawen
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
